apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: "secret-inject"
  name: "secret-inject"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      run: "secret-inject"
  template:
    metadata:
      labels:
        run : "secret-inject"
    spec:
      volumes:
        - name: certs
          secret:
            secretName: "secret-inject-tls"
      containers:
        - name: "secret-inject-init"
          image: "{{ .Values.repository}}/aws-secrets-manager-secret-adm-controller:0.2"
          volumeMounts:
            - name: certs
              mountPath: /tls
              readOnly: true
          args:
          - "--tls-cert-file=/tls/tls.crt"
          - "--tls-private-key-file=/tls/tls.key"
          - "--sidecar-image={{ .Values.repository}}/aws-secrets-manager-secret-sidecar:0.2"
          ports:
          - containerPort: 443
          imagePullPolicy: Always
