apiVersion: awssecretsoperator.secretoperator/v1
kind: SecretsRotationMapping
metadata:
  name: secretsrotationmapping-2
spec:
  SecretID: "eks-controller-test-secret"
  Labels: 
    environment: operatortest